# Generated by Django 5.0.6 on 2024-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descripcion',
            new_name='describe',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='imagen',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='title'),
        ),
    ]
