# Generated by Django 5.0.6 on 2024-08-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0002_rename_descripcion_project_describe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='<django.db.models.fields.CharField>'),
        ),
    ]
