# Generated by Django 5.0.6 on 2024-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0004_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Habilidad')),
                ('porcent', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Porcentaje_De_Habilidad')),
                ('image', models.ImageField(default=None, upload_to='image', verbose_name='Fondo')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='image', verbose_name='Portada_De_Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
    ]
