# Generated by Django 5.0.6 on 2024-08-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0005_skill_alter_project_describe_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(default=None, upload_to='icons', verbose_name='Fondo'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='porcent',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Porcentaje_De_Habilidad'),
        ),
    ]
