# Generated by Django 5.0.6 on 2024-08-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0006_alter_skill_image_alter_skill_porcent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
