# Generated by Django 5.0.6 on 2024-10-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0007_delete_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='image/', verbose_name='Portada_De_Proyecto'),
        ),
    ]
